services:
  hoot-api-gateway:
    image: hoot-api-gateway
    ports: 
      - 8005:8005
    container_name: hoot-api-gateway-composed
    depends_on:
      hoot-api-people:
        condition: service_started
      hoot-api-posts:
        condition: service_started
      hoot-api-teams:
        condition: service_started
      hoot-api-links:
        condition: service_started
      hoot-message-queues:
        condition: service_healthy
  hoot-api-people:
    image: hoot-api-people
    ports: 
      - 8001:8001
    container_name: hoot-api-people-composed
  hoot-api-posts:
    image: hoot-api-posts
    ports: 
      - 8002:8002
    container_name: hoot-api-posts-composed
  hoot-api-teams:
    image: hoot-api-teams
    ports: 
      - 8003:8003
    container_name: hoot-api-teams-composed
  hoot-api-links:
    image: hoot-api-links
    ports: 
      - 8004:8004
    container_name: hoot-api-links-composed
  hoot-message-queues:
    image: rabbitmq:3-management-alpine
    ports: 
      - 8006:5672
      - 8007:15672
    container_name: hoot-message-queues-composed
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 10
