services:

  hoot-message-queues:
    image: rabbitmq:alpine
    ports: 
      - 8006:5672
    container_name: hoot-message-queues-composed
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity || exit 1
      interval: 5s
      timeout: 2s
      retries: 3

  hoot-db-postgres:
    image: postgres:alpine
    ports:
      - 8008:5432
    container_name: hoot-db-postgres-composed
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=guest
      - POSTGRES_DB=hoot
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 5s
      timeout: 2s
      retries: 3

  hoot-db-mongo:
    image: mongo
    ports:
      - 8009:27017
    container_name: hoot-db-mongo-composed
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=guest
      - DB_NAME=hoot
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet || exit 1
      interval: 5s
      timeout: 2s
      retries: 3

  hoot-api-people:
    image: hoot-api-people
    ports: 
      - 8001:8001
    container_name: hoot-api-people-composed
    depends_on:
      hoot-message-queues:
        condition: service_healthy
      hoot-db-postgres:
        condition: service_healthy

  hoot-api-posts:
    image: hoot-api-posts
    ports: 
      - 8002:8002
    container_name: hoot-api-posts-composed
    depends_on:
      hoot-message-queues:
        condition: service_healthy
      hoot-db-postgres:
        condition: service_healthy


  hoot-api-teams:
    image: hoot-api-teams
    ports: 
      - 8003:8003
    container_name: hoot-api-teams-composed
    depends_on:
      hoot-message-queues:
        condition: service_healthy
      hoot-db-mongo:
        condition: service_healthy

  hoot-api-links:
    image: hoot-api-links
    ports: 
      - 8004:8004
    container_name: hoot-api-links-composed
    depends_on:
      hoot-message-queues:
        condition: service_healthy
      hoot-db-mongo:
        condition: service_healthy

  hoot-api-gateway:
    image: hoot-api-gateway
    ports: 
      - 8005:8005
    container_name: hoot-api-gateway-composed
    depends_on:
      hoot-message-queues:
        condition: service_healthy
      hoot-api-people:
        condition: service_started
      hoot-api-posts:
        condition: service_started
      hoot-api-teams:
        condition: service_started
      hoot-api-links:
        condition: service_started
